apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eap-prod

resources:
  - ../../base

images:
  - name: REGISTRY/eap
    newName: REGISTRY/eap
    newTag: "1.0.0" # pinned by CI/CD to the released image digest/tag

replicas:
  - name: eap
    count: 3

patches:
  - path: resources-patch.yaml
    target:
      kind: Deployment
      name: eap
