apiVersion: apps/v1
kind: Deployment
metadata:
  name: eap
spec:
  template:
    spec:
      containers:
        - name: eap
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "2Gi"
